### ISSUE TITLE
Direct DOM manipulation

### ISSUE THREAD

**Issue by anirudhsama** [shubhamkumbhakar/supernova#1]
Why is this part of the DOM manipulated directly?

https://github.com/shubhamkumbhakar/supernova/blob/e7568193cc79a659446a95fd19544af9bf5cd984/src/Components/Quiz/index.jsx#L131

**Comment by shubhamkumbhakar** [comment]
This was added for directly checking the DOM structure. Now this has been replaced with dynamic className: `check_message` and `hide` as per the requirement.
